### ISSUE TITLE
Line break boundary definition

### ISSUE THREAD

**Issue by xinyuluo** [dbuenzli/uuseg#10]
Hi! I am having some issues with the `Line_break` separator, it seems like it considers `\0x20` (white space) as a breaking point, is this expected?

**Comment by dbuenzli** [comment]
Well space is a [line break opportunity](https://www.unicode.org/reports/tr14/#BreakOpportunities) if you are only looking for mandatory line breaks [use this function](https://erratique.ch/software/uuseg/doc/Uuseg/index.html#val-mandatory).

**Comment by xinyuluo** [comment]
Thank you for the swift reply! May I just follow up on this: what if i need to use `val fold_utf_8 : [< [Uuseg.boundary] ] -> 'a [folder] -> 'a -> string -> 'a`, whose input has type Uuseg.boundary?

**Comment by dbuenzli** [comment]
These convenience function report all boundaries regardless. You will have to devise our own.

**Comment by dbuenzli** [comment]
See [this example](https://erratique.ch/software/uuseg/doc/Uuseg/index.html#examples)
