### ISSUE TITLE
preserve words connected with a hyphen

### ISSUE THREAD

**Issue by xinyuluo** [dbuenzli/uuseg#9]
Hi! I noticed that words containing a hyphen would be split into two based on the `Word` boundary, for instance:
```
# Uuseg_string.fold_utf_8 `Word (fun x s -> s :: x) [] "in-depth" |> List.rev;;
- : string list = ["in"; "-"; "depth"]
```
Is there a way to go around this and keep them as one word (i.e. "in-depth")? 

Thank you!

**Comment by dbuenzli** [comment]
I'm afraid not. That's the way the [standard](https://www.unicode.org/reports/tr29/#Word_Boundaries) segments:

> The correct interpretation of hyphens in the context of word boundaries is challenging. It is quite common for separate words to be connected with a hyphen: “out-of-the-box,” “under-the-table,” “Italian-American,” and so on. A significant number are hyphenated names, such as “Smith-Hawkins.” When doing a Whole Word Search or query, users expect to find the word within those hyphens. While there are some cases where they are separate words (usually to resolve some ambiguity such as “re-sort” as opposed to “resort”), it is better overall to keep the hyphen out of the default definition.

You can likely work around by pre or post processing your inputs to get what you want.
